# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('question_no', models.IntegerField(blank=True, default=1)),
                ('answers_given', models.CharField(default='000000', max_length=100)),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(blank=True, default=1)),
                ('question', models.CharField(max_length=10000)),
                ('solution', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
