# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemhunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='answers_given',
            field=models.CharField(default='000000000000000000000000000000000000', max_length=100),
        ),
    ]
